# See http://www.appveyor.com/docs/appveyor-yml for many more options

image: Visual Studio 2017
version: '1.0.{build}'
clone_folder: c:\projects\PSKoans

environment:
  NugetApiKey:
    secure: G4KH7AVKvqA+2gNNtmnF1YxP9r2MWe55HbTy9no7fmACcNj6tXy0l4VKMOR8s0lx

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
- ps: . .\build\build.ps1